repos:
  - repo: local
    hooks:
      - id: format frontend
        name: format frontend
        language: system
        entry: bash -c "cd frontend && npm run format"
      - id: format backend
        name: format backend
        language: system
        entry: bash -c "cd backend && go fmt"
